# - Locate Heppy Setup
# Defines:

# find_path(HEPPY_DIR modules/heppy/main_python HINTS $ENV{HEPPYDIR})
set(HEPPYSET $ENV{HEPPYDIR})
if (HEPPYSET)
	set(Python_NumPy_INCLUDE_DIRS $ENV{HEPPY_PYTHON_NUMPY_INCLUDE_DIR})
	set(Python_INCLUDE_DIRS $ENV{HEPPY_PYTHON_INCLUDE_DIR})
	set(Python_LIBRARIES $ENV{HEPPY_PYTHON_CONFIG_LDFLAGS})
	set(Python_EXECUTABLE $ENV{HEPPY_PYTHON_EXECUTABLE})
	set(Python_FOUND 1)
endif(HEPPYSET)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HEPPY DEFAULT_MSG HEPPYSET Python_NumPy_INCLUDE_DIRS Python_INCLUDE_DIRS Python_LIBRARIES Python_EXECUTABLE)