# Processing parameters
jetR: [0.2]
alphas: [1, 1.5, 2, 3]

# Initial detector-level binnings. Distributions are rebinned via configs before unfolding
n_pt_bins: 195
pt_limits: [5, 200]
n_lambda_bins: 160
lambda_limits: [0, 0.8]
n_rap_bins: 20            # just for fun, look at lambda distribution vs rapidity
rap_limits: [-0.5, 0.5]

# For extra verbose output in some functions
debug_level: 0

process_observables: ['ang']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0

# SoftDrop setting (current same for all SD plots)
sd_zcut: 0.2    # multiplier
sd_beta: 0      # exponent on (deltaR / R)


###############################################################################
# Rebinning and unfolding parameters/configurations for angularity observables
ang:

  common_settings:
    xtitle: '#it{#lambda}_{#it{#alpha}}^{#it{#kappa}=1}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#lambda}_{#it{#alpha}}^{#it{#kappa}=1}}'
    pt_bins_reported: [80, 100]
    plot_overlay_list:
      - ['config_R0.2_1', 'config_R0.2_1.5', 'config_R0.2_2', 'config_R0.2_3']
      - ['config_R0.2_1_SD', 'config_R0.2_1.5_SD', 'config_R0.2_2_SD', 'config_R0.2_3_SD']
    max_reg_param: 10

  ############################################################################
  # Different R & alpha configurations
  config_R0.2_1:
    R: 0.2
    alpha: 1
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
    obs_bins_truth: [0, 0.1, 0.15, 0.2, 0.25, 0.3, 0.5, 0.75]
    obs_max_reported: [0.5]
    obs_bins_det: [0, 0.1, 0.15, 0.20, 0.25, 0.3, 0.5, 0.75]
    obs_bins_det_sys_binning: [0, 0.09, 0.14, 0.19, 0.24, 0.32, 0.52, 0.75]
    reg_param:
      0.2: 3

  config_R0.2_1.5:
    R: 0.2
    alpha: 1.5
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
    obs_bins_truth: [0, 0.04, 0.08, 0.12, 0.17, 0.35, 0.6]
    obs_max_reported: [0.35]
    obs_bins_det: [0, 0.04, 0.08, 0.12, 0.17, 0.35, 0.6]
    obs_bins_det_sys_binning: [0, 0.045, 0.075, 0.11, 0.16, 0.38, 0.6]
    reg_param:
      0.2: 3

  config_R0.2_2:
    R: 0.2
    alpha: 2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
    obs_bins_truth: [0, 0.02, 0.04, 0.07, 0.1, 0.25, 0.5]
    obs_max_reported: [0.25]
    obs_bins_det: [0, 0.02, 0.04, 0.07, 0.1, 0.25, 0.5]
    obs_bins_det_sys_binning: [0, 0.025, 0.045, 0.085, 0.13, 0.27, 0.5]
    reg_param:
      0.2: 3

  config_R0.2_3:
    R: 0.2
    alpha: 3
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
    obs_bins_truth: [0, 0.01, 0.02, 0.04, 0.07, 0.1, 0.4]
    obs_max_reported: [0.1]
    obs_bins_det: [0, 0.01, 0.02, 0.04, 0.07, 0.1, 0.4]
    obs_bins_det_sys_binning: [0, 0.005, 0.015, 0.035, 0.075, 0.11, 0.4]
    reg_param:
      0.2: 3

  ############################################################################
  # Different R & alpha configurations
  config_R0.2_1_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.2
    alpha: 1
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
    obs_bins_truth: [0, 0.05, 0.1, 0.2, 0.3, 0.45, 0.7]
    obs_max_reported: [0.45]
    obs_bins_det: [0, 0.05, 0.1, 0.2, 0.3, 0.45, 0.7]
    obs_bins_det_sys_binning: [0, 0.04, 0.08, 0.17, 0.26, 0.47, 0.7]
    reg_param:
      0.2: 3

  config_R0.2_1.5_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.2
    alpha: 1.5
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
    obs_bins_truth: [0, 0.02, 0.05, 0.1, 0.35, 0.6]
    obs_max_reported: [0.35]
    obs_bins_det: [0, 0.02, 0.05, 0.1, 0.35, 0.6]
    obs_bins_det_sys_binning: [0, 0.025, 0.06, 0.11, 0.37, 0.6]
    reg_param:
      0.2: 3

  config_R0.2_2_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.2
    alpha: 2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
    obs_bins_truth: [0, 0.005, 0.01, 0.03, 0.08, 0.25, 0.5]
    obs_max_reported: [0.25]
    obs_bins_det: [0, 0.005, 0.01, 0.03, 0.08, 0.25, 0.5]
    obs_bins_det_sys_binning: [0, 0.005, 0.015, 0.035, 0.1, 0.28, 0.5]
    reg_param:
      0.2: 3

  config_R0.2_3_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.2
    alpha: 3
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
    obs_bins_truth: [0, 0.001, 0.005, 0.02, 0.05, 0.1, 0.3]
    obs_max_reported: [0.1]
    obs_bins_det: [0, 0.001, 0.005, 0.02, 0.05, 0.1, 0.3]
    obs_bins_det_sys_binning: [0, 0.002, 0.007, 0.015, 0.055, 0.15, 0.3]
    reg_param:
      0.2: 3


###############################################################################
# Theory comparison parameters
do_theory_comp: True
theory_alpha: [1.5, 2, 3]
theory_dir: "/home/ezra/theory_predictions/"
pt_scale_factors_filename: "qg_fractions-ALICE-R02.txt"
response_levels: [["p", "ch", "off"], ["p", "h", "off"], ["h", "ch", "on"]]
theory_pt_bins: [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100,
                 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]
Omega_list: [0.2, 0.4, 0.8, 2]
response_files: ["/rstorage/alice/AnalysisResults/ang/353823/AnalysisResultsFinal.root",
                 "/rstorage/alice/AnalysisResults/ang/344912/AnalysisResultsFinal.root"]
response_labels: ["PYTHIA8", "Herwig7"]
rebin_theory_response: False


###############################################################################
# Analysis & plotting parameters
file_format: ".pdf"
output_dir: "/rstorage/alice/AnalysisResults/ang/AngR02_ptbin4"
roounfold_path: "/home/ezra/heppy/external/roounfold/roounfold-current/lib/libRooUnfold.so"

analysis_observable: 'ang'
do_unfolding: False
force_rebin: False
do_systematics: True
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: 'Preliminary'

# Whether or not to use the previous preliminary result in final results
use_prev_prelim: False

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning, \
#           random_mass, fastsim_generator0, fastsim_generator1]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - random_mass
  - fastsim_generator0
  - fastsim_generator1

# Paths to processing output, to be used for unfolding
main_data: '/rstorage/alice/AnalysisResults/ang/287220/AnalysisResultsFinal.root'
main_response: '/rstorage/alice/AnalysisResults/ang/351487/AnalysisResultsFinal.root'
trkeff_response: '/rstorage/alice/AnalysisResults/ang/351489/AnalysisResultsFinal.root'
randmass_data: '/rstorage/alice/AnalysisResults/ang/287383/AnalysisResultsFinal.root'
randmass_response: '/rstorage/alice/AnalysisResults/ang/351488/AnalysisResultsFinal.root'
fastsim_response: ['/rstorage/alice/AnalysisResults/ang/287385/AnalysisResultsFinal.root',
                   '/rstorage/alice/AnalysisResults/ang/287386/AnalysisResultsFinal.root']

# Prior variation parameters
prior_variation_option: 1
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
